### PR TITLE
Support windows

### PR DESCRIPTION
**Pull request by usmanyunusov**

### CODE REVIEW

**Comment by iambumblehead** [comment]
@usmanyunusov I'm lurking this package because it is one of the few to use esmock.

esmock was updated recently to support windows https://github.com/iambumblehead/esmock/issues/20

You may have simply lost interest in this package, but I'm letting you know the windows issue is resolved.

**Comment by usmanyunusov** [comment]
I want to use esmock with a uvu (https://github.com/lukeed/uvu). Did not work out.

**Comment by iambumblehead** [comment]
@usmanyunusov thanks I'll try adding uvu tests the ava ones inside esmock

**Comment by iambumblehead** [comment]
@usmanyunusov uvu tests are passing here https://github.com/iambumblehead/esmock/pull/35
```json
{
  "test-uvu": "node --no-warnings --loader=./src/esmockLoader.mjs ./node_modules/uvu/bin.js ./spec/uvu/"
}
```

**Comment by usmanyunusov** [comment]
@iambumblehead It works at OS Win is?

**Comment by iambumblehead** [comment]
@usmanyunusov yes windows filepaths fixed a few days ago here https://github.com/iambumblehead/esmock/issues/20 and esmock now includes windows-latest test pipeline

**Comment by usmanyunusov** [comment]
@iambumblehead Thanks! I will fix tests.

**Pull request merged**
